import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Infobar from '../components/Infobar'
import styles from '../styles/Home.module.css'

const Home: NextPage = ({ categories }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trickyzon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header categories={categories} />
    <Infobar />
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('https://fakestoreapi.com/products/categories')
  const categories = await res.json()

  return {
    props: { categories }
  }
}

export default Home
